
services:
  mlflow:
    build: .  # Dockerfile을 사용해 이미지 빌드
    container_name: mlflow_server
    ports:
      - "5000:5000"  # 포트 매핑
    volumes:
      - ./mlruns:/mlflow/mlruns  # 모델 아티팩트를 로컬과 컨테이너간 마운트 
    environment:
      - MLFLOW_TRACKING_URI=postgresql://postgres:connectslab@172.31.29.95:5432/mlflow_db
      - MLFLOW_ARTIFACT_ROOT=/mlflow/mlruns
    command: >
      mlflow server 
      --backend-store-uri postgresql://postgres:connectslab@172.31.29.95:5432/mlflow_db
      --default-artifact-root /mlflow/mlruns 
      --host 0.0.0.0 
      --port 5000