services:
  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka1
    network_mode: host
    environment:
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: '1'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@172.31.28.191:9093,2@172.31.29.95:9093,3@172.31.17.183:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://172.31.28.191:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_LOG_RETENTION_HOURS: '168'  # 로그 잔존 시간을 7일로 설정
      KAFKA_MESSAGE_MAX_BYTES: 2097152  # 메시지 크기를 2MB로 설정
      KAFKA_MAX_REQUEST_SIZE: 2097152   
    volumes:
      - /home/ubuntu/instance1/kafka/kafka_data:/var/lib/kafka/data
